### ISSUE TITLE
Draw up Class Diagram

### ISSUE THREAD

**Issue by VriesDeRick** [VriesDeRick/horus#16]

**Comment by VriesDeRick** [comment]
![image](https://user-images.githubusercontent.com/11596702/52342943-0f405700-2a17-11e9-9fdc-7dc98ed8544b.png)
Will still need to be made into a "nice" digital diagram

**Comment by JustinPraas** [comment]
Nice camera quality!

**Comment by VriesDeRick** [comment]
Class Diagram was made in draw.io and can be found on GDrive.
